name: DrugMeUp
main: me.giinger.dmu.Drugs
version: 0.8.3
author: Giinger, hammale
commands:
  drugmeup:
    description:
    usage: "Incorrect usage. '/drugmeup [cleardrugs/reload]'"
    
permissions:
    drugs.*:
        description: Gives access to all DrugMeUp features
        children:
            drugs.use: true
            drugs.reload: true
            drugs.cleardrugs: true
            drugs.updates: true
    drugs.updates:
        description: Shows members who login when there's an update for DrugMeUp
        default: op
    drugs.use:
        description: Allows users to do drugs
        default: op    
    drugs.reload:
        description: Reloads the config
        default: op    
    drugs.cleardrugs:
        description: Clears drugs from player
        default: op